### ISSUE TITLE
Question: merge ftd2xx-embedded-hal and ftdi-embedded-hal

### ISSUE THREAD

**Issue by geomatsi** [newAM/ftd2xx-embedded-hal#34]
Hi @newAM 

I planned to work on some updates for ```ftdi-embedded-hal``` including i2c fixes, gpio input support, mpsse  commands handling and probably some other topics. Meanwhile some time ago I discovered your project ```ft2xx-embedded-hal```. So I took a look at this project to compare approaches and probably to get some new ideas. I really liked what I saw, in particular your approach to MPSSE handling using command builder. My first intention was to port that approach to ```ftdi-embedded-hal```. However after pondering a little bit about it, I think that a more reasonable option is to merge ```ftdi-embedded-hal``` into ```ftd2xx-embedded-hal``` adding some kind of ```libftdi``` _backend_.

From my perspective the plan looks as follows:

- [ ] to split MPSSE command builder from ```libftd2xx-rs``` into a separate crate
- [ ] to remove MPSSE related code duplication from ```libftd2xx-rs``` using this new crate
- [ ] to extract low-level ```libftd2xx``` parts of ```ftd2xx-embedded-hal``` into a separate layer, e.g. using traits to define FTDI _backend_ low-level operations such as open/read/write
- [ ] to add ```libftdi``` support to your HAL, e.g. using Cargo features to choose between ```libftdi``` and ```libftd2xx``` 
- [ ] to continue adding features (e.g. gpio input) testing both _backends_

Naturally, before starting to hack around your crates and sending PRs, I would like to know what do you think about it.

Regards,
Sergey

**Comment by newAM** [comment]
> to split MPSSE command builder from libftd2xx-rs into a separate crate

Sounds good to me!  There may be some `libftd2xx` specific commands, I _think_ there may be some in-band signaling.  I am not sure if commands like `send_immediate` get sent to the device or if that is stripped in the `libftd2xx` driver.  This shouldn't be too hard to figure out by looking at what `libftdi` does.

> to remove MPSSE related code duplication from libftd2xx-rs using this new crate

Yup, that sounds good.

> to extract low-level libftd2xx parts of ftd2xx-embedded-hal into a separate layer, e.g. using traits to define FTDI backend low-level operations such as open/read/write

The `libftdi` approach has the advantage of being able to adapt to `std::io::Error` easily, but `libftd2xx` does not.

It would be a little less elegant for `libftdi`, but I think the best approach would be an associated error type so that the native errors can be returned, e.g.

```rs
pub trait FtdiRead {
   type Error;
   fn read(&mut self, &[u8]) -> Result<usize, Self::Error>;
   // or maybe this?  Not sure what fits well with libftdi
   fn read_all(&mut self, &[u8]) -> Result<(), Self::Error>;
}
```

> to add libftdi support to your HAL, e.g. using Cargo features to choose between libftdi and libftd2xx

I am ok with this, but I do have some requirements that might make it difficult:

* No conditional compilation or non-additive feature flags.  I really like to avoid incompatible feature flags where possible because [cargo expects features to be additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification).  I know I sort of break this rule with static/dynamic linking features in this crate, but those do not actually change the code.
* No additional compile time requirements for any targets.  I find development tools become significantly less useful when they take a while to setup.  `libftdi` is not easy to get working on Windows (through no fault of its own, Windows is hostile for anything related to USB device development in my opinion).

Those requirements really narrow down what can be done for the implementation, the only way I could think of doing this would be extracting the traits into a separate crate (perhaps the MPSSE crate?) such that the FTDI HAL does not have to link to either `libftd2xx` or `libftdi` at compile time.  Then the users of the FTDI HAL would include both the HAL and their back-end of choice (or even both back-ends).

I am not sure if this lines up with what you have in mind; any thoughts?

**Comment by geomatsi** [comment]
On the first glance the requirements appear to be quite restrictive. Unless I am missing something, licensing is one of the major differences between ```libftdi``` and ```libftd2xx``` (well, at least in the case if we assume that they both cover basic functionality required to implement i2c/spi/gpio). But I am not sure if clear license terms can be achieved without conditional compilation. Some kind of _dlopen_ approach looks fragile... 

One possible idea that comes to mind is to maintain both HALs sharing core MPSSE functionality between them. For instance, consider the following split into layers:
- _frontend_: select/open/configure operations on FTDI device
- MPSSE protocols: i2c/spi/gpio implementation on top of MPSSE commands 
- MPSSE commands: most part is already implemented in ```libftd2xx-rs```
- _backend_: read/write/flush operations on the selected FTDI device

It looks like the two MPSSE layers in the middle can be implemented in a libftxx-agnistic way.

Regards,
Sergey

**Comment by newAM** [comment]
> On the first glance the requirements appear to be quite restrictive. Unless I am missing something, licensing is one of the major differences between `libftdi` and `libftd2xx` (well, at least in the case if we assume that they both cover basic functionality required to implement i2c/spi/gpio). But I am not sure if clear license terms can be achieved without conditional compilation. Some kind of _dlopen_ approach looks fragile...

The idea I had in mind was completely skipping this problem by not having the back-ends part of the dependencies for the HAL.

```text
ftdihal
└── ftdimpsse

--- separate crate ---

libftd2xx
├── libftd2xx-ffi
└── ftdimpsse

--- separate crate ---

libftdi1
├── libftdi1-sys
└── ftdimpsse
```

`ftdimpsse` would define the traits for common FTDI functionality, e.g.
```rs
pub trait FtdiRead {
   type Error;
   fn read(&mut self, &mut [u8]) -> Result<usize, Self::Error>;
}
pub trait FtdiWrite {
   type Error;
   fn write(&mut self, &[u8]) -> Result<usize, Self::Error>;
}
```

Then `libftdi1` and `libftd2xx` would implement those traits.  The HAL could either offer an extension trait that is implemented for the types in `libftdi`/`libftd2xx` that implement the trait:
```rs
impl<FTDI, E> FtdiHalFunctionality<E> for FTDI
where
    FTDI: FtdiRead<Error = E> + FtdiWrite<Error = E>
{}
```
or maybe a generic structure:
```rs
struct FtdiHal<FTDI> {
    ftdi: FTDI
}

impl<FTDI, E> FtdiHal<FTDI: FtdiRead<Error = E> + FtdiWrite<Error = E>> {
}
```

For the user this would mean they would have something like this in their `Cargo.toml`:
```toml
[dependencies]
ftdihal = "0"
# one or more of these
libftd2xx = "0"
libftdi1 = "0"
```

This would lead to code that fits better with the cargo system, and optionally the ability to support both back-ends simultaneously (could be useful on Windows to select `libftdi1`/`ftd2xx` at runtime depending on which USB driver is in-use for the device).

> One possible idea that comes to mind is to maintain both HALs sharing core MPSSE functionality between them. For instance, consider the following split into layers:

That is another option; it would be advantageous in that the setup can be tailored to what each driver exposes, and the SPI/UART/I2C functionality would still be portable via the `embedded-hal` traits.

**Comment by geomatsi** [comment]
Looks interesting, though I don't quite understand how cargo will resolve the presence of both ```libftd2xx-rs``` and ```libftdi```. By the way, what about the following simplified approach:
* ```ftdihal``` _implements_ ```embedded-hal``` traits
* ```ftdihal``` is built on top of low level traits for FTDI device operations like open/select device, configure MPSSE modes, read/write in MPSSE mode
* both ```libftd2xx-rs``` and ```libftdi``` implement those low level traits

In this case the end user will specify either ```libftd2xx-rs``` or ```libftdi``` depending on its preferences in terms of licensing, platform, etc.

Regards, 
Sergey

**Comment by newAM** [comment]
> In this case the end user will specify either libftd2xx-rs or libftdi depending on its preferences in terms of licensing, platform, etc.

I think we are thinking of the same thing now, maybe just with different ideas of implementation.

In the way I suggested `libftd2xx` vs `libftdi1` would be selected via the user including that crate in their `Cargo.toml`, instead of conditional compilation with non-additive flags.

> Looks interesting, though I don't quite understand how cargo will resolve the presence of both libftd2xx-rs and libftdi.

They are independent libraries, linking both will not result in any incompatibilities.  The types for the HAL would be generic for any driver; the conrete types would be different depending on the driver.  Same idea as how SPI device drivers work with embedded HAL traits, e.g.

```rs
struct Bme280<SPI> {
    spi: SPI
}
```

That can be implemented for anything that implements the embedded-hal SPI traits, same idea for FTDI devices; create a generic `FtdiHal` that can be implemented for anything that implements the FTDI traits.

**Comment by geomatsi** [comment]
Ok. Thanks for sharing your ideas! I will add more examples for testing and start from extracting ```ftdimpsse``` layer from your ```libftd2xx```. 

Regards,
Sergey

**Comment by newAM** [comment]
Archiving this crate, closing the issue since https://github.com/ftdi-rs/ftdi-embedded-hal exists now :+1: 

Thanks for all your work on this @geomatsi !
